name: vast-tools
version: 0.1.0.0
github: "githubuser/vast-tools"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/vast-tools#readme>

dependencies:
  - base >= 4.7 && < 5
  - lens
  - xml-conduit
  - xml-lens
  - text
  - bytestring
  - servant
  - http-media
  - openapi3
  - containers
  - first-class-families
  - case-insensitive
  - modern-uri

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -Wall

tests:
  vast-tools-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - vast-tools
